# Generated by Django 6.0.3 on 2026-03-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre de la Licitación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción General')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación (Ciudad/Coordenadas)')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('deadline', models.DateTimeField(verbose_name='Fecha Límite (Cierre) para Ofertas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('CLOSED', 'Cerrada / Evaluación'), ('AWARDED', 'Adjudicada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('awarded_contractor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Contratista Ganador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
