# Generated by Django 6.0.3 on 2026-03-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='official_aiu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total AIU ($)'),
        ),
        migrations.AddField(
            model_name='project',
            name='official_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Directo PEPC (Suma Ítems)'),
        ),
        migrations.AddField(
            model_name='project',
            name='official_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total IVA ($)'),
        ),
        migrations.AddField(
            model_name='project',
            name='official_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Gran Total Estimado PEPC ($)'),
        ),
    ]
