# Generated by Django 6.0.3 on 2026-03-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_official_aiu_project_official_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='limit_j297',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Límite Inferior (Casilla J297)'),
        ),
        migrations.AddField(
            model_name='project',
            name='limit_lm297',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Límite Superior (Casilla LM297)'),
        ),
    ]
