# Generated by Django 6.0.3 on 2026-03-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiuDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Administración')),
                ('unforeseen_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Imprevistos')),
                ('utility_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Utilidad')),
                ('iva_percent', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='% IVA (Sobre Utilidad o Pleno)')),
                ('iva_on_utility_only', models.BooleanField(default=True, verbose_name='¿El IVA aplica solo sobre la utilidad?')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aiu_definition', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código del Ítem (Ej: 1.1)')),
                ('description', models.TextField(verbose_name='Descripción de la Actividad')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad de Medida (Ej: m2, kg, un)')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad Total')),
                ('official_unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Unitario PEPC (Oficial)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.project')),
            ],
        ),
    ]
