# Generated by Django 6.0.3 on 2026-03-06 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_official_aiu_project_official_budget_and_more'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=255, verbose_name='Nombre del Contratista / Razón Social')),
                ('contractor_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico del Contratista')),
                ('total_budget_offered', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Costo Directo Ofertado')),
                ('total_aiu_offered', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='AIU Ofertado')),
                ('total_iva_offered', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='IVA Ofertado')),
                ('grand_total_offered', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Gran Total Ofertado')),
                ('deviation_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='% Desviación vs PEPC')),
                ('semaphore_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color Asignado (Verde, Naranja, Rojo)')),
                ('ranking_position', models.IntegerField(blank=True, null=True, verbose_name='Posición en el Ranking (Top 3)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador (Editando)'), ('SUBMITTED', 'Enviada / Consolidada')], default='DRAFT', max_length=20, verbose_name='Estado de la Oferta')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío Final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio Unitario Ofertado')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones (Contratista)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_prices', to='tenders.item')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_prices', to='offers.contractoroffer')),
            ],
        ),
    ]
