/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CounterofferRouteImport } from './routes/counteroffer'
import { Route as BiddingRouteImport } from './routes/bidding'
import { Route as IndexRouteImport } from './routes/index'

const CounterofferRoute = CounterofferRouteImport.update({
  id: '/counteroffer',
  path: '/counteroffer',
  getParentRoute: () => rootRouteImport,
} as any)
const BiddingRoute = BiddingRouteImport.update({
  id: '/bidding',
  path: '/bidding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bidding': typeof BiddingRoute
  '/counteroffer': typeof CounterofferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bidding': typeof BiddingRoute
  '/counteroffer': typeof CounterofferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bidding': typeof BiddingRoute
  '/counteroffer': typeof CounterofferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bidding' | '/counteroffer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bidding' | '/counteroffer'
  id: '__root__' | '/' | '/bidding' | '/counteroffer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiddingRoute: typeof BiddingRoute
  CounterofferRoute: typeof CounterofferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/counteroffer': {
      id: '/counteroffer'
      path: '/counteroffer'
      fullPath: '/counteroffer'
      preLoaderRoute: typeof CounterofferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bidding': {
      id: '/bidding'
      path: '/bidding'
      fullPath: '/bidding'
      preLoaderRoute: typeof BiddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiddingRoute: BiddingRoute,
  CounterofferRoute: CounterofferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
