/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CounterofferRouteImport } from './routes/counteroffer'
import { Route as BiddingRouteImport } from './routes/bidding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdTendersIndexRouteImport } from './routes/projects/$projectId/tenders/index'
import { Route as ProjectsProjectIdEvaluationIndexRouteImport } from './routes/projects/$projectId/evaluation/index'

const CounterofferRoute = CounterofferRouteImport.update({
  id: '/counteroffer',
  path: '/counteroffer',
  getParentRoute: () => rootRouteImport,
} as any)
const BiddingRoute = BiddingRouteImport.update({
  id: '/bidding',
  path: '/bidding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdTendersIndexRoute =
  ProjectsProjectIdTendersIndexRouteImport.update({
    id: '/projects/$projectId/tenders/',
    path: '/projects/$projectId/tenders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdEvaluationIndexRoute =
  ProjectsProjectIdEvaluationIndexRouteImport.update({
    id: '/projects/$projectId/evaluation/',
    path: '/projects/$projectId/evaluation/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bidding': typeof BiddingRoute
  '/counteroffer': typeof CounterofferRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/evaluation/': typeof ProjectsProjectIdEvaluationIndexRoute
  '/projects/$projectId/tenders/': typeof ProjectsProjectIdTendersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bidding': typeof BiddingRoute
  '/counteroffer': typeof CounterofferRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/evaluation': typeof ProjectsProjectIdEvaluationIndexRoute
  '/projects/$projectId/tenders': typeof ProjectsProjectIdTendersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bidding': typeof BiddingRoute
  '/counteroffer': typeof CounterofferRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/evaluation/': typeof ProjectsProjectIdEvaluationIndexRoute
  '/projects/$projectId/tenders/': typeof ProjectsProjectIdTendersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bidding'
    | '/counteroffer'
    | '/projects/'
    | '/projects/$projectId/evaluation/'
    | '/projects/$projectId/tenders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bidding'
    | '/counteroffer'
    | '/projects'
    | '/projects/$projectId/evaluation'
    | '/projects/$projectId/tenders'
  id:
    | '__root__'
    | '/'
    | '/bidding'
    | '/counteroffer'
    | '/projects/'
    | '/projects/$projectId/evaluation/'
    | '/projects/$projectId/tenders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiddingRoute: typeof BiddingRoute
  CounterofferRoute: typeof CounterofferRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdEvaluationIndexRoute: typeof ProjectsProjectIdEvaluationIndexRoute
  ProjectsProjectIdTendersIndexRoute: typeof ProjectsProjectIdTendersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/counteroffer': {
      id: '/counteroffer'
      path: '/counteroffer'
      fullPath: '/counteroffer'
      preLoaderRoute: typeof CounterofferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bidding': {
      id: '/bidding'
      path: '/bidding'
      fullPath: '/bidding'
      preLoaderRoute: typeof BiddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/tenders/': {
      id: '/projects/$projectId/tenders/'
      path: '/projects/$projectId/tenders'
      fullPath: '/projects/$projectId/tenders/'
      preLoaderRoute: typeof ProjectsProjectIdTendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/evaluation/': {
      id: '/projects/$projectId/evaluation/'
      path: '/projects/$projectId/evaluation'
      fullPath: '/projects/$projectId/evaluation/'
      preLoaderRoute: typeof ProjectsProjectIdEvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiddingRoute: BiddingRoute,
  CounterofferRoute: CounterofferRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdEvaluationIndexRoute: ProjectsProjectIdEvaluationIndexRoute,
  ProjectsProjectIdTendersIndexRoute: ProjectsProjectIdTendersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
